### PR TITLE
Updating PHP version (7.1 --> 7.2)

### PR DESCRIPTION
**Pull request by hgunicamp**
Updating PHP version (7.1 --> 7.2)

### CODE REVIEW

**Comment by ivan-pinatti** [comment]
Hi @hgunicamp,

Could you please rewrite the code to have less layers in the Docker image?

When you are doing multiple RUN or COPY commands you are creating one layer each, which will make the Docker image bigger. That's why the previous version was broke down with fewer Docker commands and lots of Linux concatenations (&&). The mindset there was that every "step" during the image baking would be a layer .

Just to give you an example, you are adding 11 layers through the PECL install calls, it would be better to have one Docker command with concatenations so it would be just one Docker layer in the image.

Cheers!

**Comment by hgunicamp** [comment]
Hi @ivan-pinatti.

I fixed the issue you have mentioned previously.
I believed everything is fine now.

**Comment by ivan-pinatti** [comment]
Hi @hgunicamp,

Looks better now, thanks!
However, since I am not leading the project anymore I would wait for @rodrigoeg OR @erickj-ciandt approval.

Cheers!

**Comment by rodrigoeg** [comment]
Thank you @hgunicamp  and @ivan-pinatti 

I merged the PR in a new branch for php7.2 (the branch name convention will have to be reviewed later).

**Pull request merged**
